up:
	docker-compose up -d

down:
	docker-compose down

sh:
	docker exec -it example_php sh

cc:
	docker exec -it example_php bin/console cache:clear

composer-install:
	docker exec -it example_php composer install
