# Use the official Nginx base image
FROM nginx:latest

MAINTAINER Kamil Nawrotkiewicz <kamil.nawrotkiewicz@innovcode.it>

# Copy the custom Nginx configuration file
COPY docker/local/nginx/default.conf /etc/nginx/conf.d/default.conf
